//Fetch
export const REQUEST_PENDING = 'REQUEST_PENDING';
export const REQUEST_RESOLVED = 'REQUEST_RESOLVED';
export const REQUEST_REJECTED = 'REQUEST_REJECTED';

//Cart
export const LOADING_CARTLIST = 'LOADING_CARTLIST';
export const CARTLIST_SUCCESS = 'CARTLIST_SUCCESS';
export const ADD_CARTITEM = 'ADD_CARTITEM';
export const UPDATE_CARTITEM = 'UPDATE_CARTITEM';
export const REMOVE_CARTITEM = 'REMOVE_CARTITEM';
export const CHANGE_QUANTITY = 'CHANGE_QUANTITY';
export const CALCULATE_QTYANDPRICE = 'CALCULATE_QTYANDPRICE';
export const SAVE_PAYINFO = 'SAVE_PAYINFO';

//Authentication
export const LOADING_AUTH = 'LOADING_AUTH';
export const GET_AUTHINFO = 'GET_AUTHINFO';
export const UPDATE_USERDATA = 'UPDATE_USERDATA';
export const LOGOUT_AUTH = 'LOGOUT_AUTH';
