//Fetch
export const LOADING_REQUEST = 'LOADING_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAIL = 'REQUEST_FAIL';

//Products
export const LOADING_PRODUCTS = 'LOADING_PRODUCTS';
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS';
export const PRODUCTS_FAIL = 'PRODUCTS_FAIL';
export const LOADING_PRODUCT = 'LOADING_PRODUCT';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_FAIL = 'PRODUCT_FAIL';

//Cart
export const LOADING_CARTLIST = 'LOADING_CARTLIST';
export const CARTLIST_SUCCESS = 'CARTLIST_SUCCESS';
export const ADD_CARTITEM = 'ADD_CARTITEM';
export const REMOVE_CARTITEM = 'REMOVE_CARTITEM';
export const CHANGE_QUANTITY = 'CHANGE_QUANTITY';
export const CALCULATE_QTYANDPRICE = 'CALCULATE_QTYANDPRICE';
export const SAVE_PAYINFO = 'SAVE_PAYINFO';

//Authentication
export const LOADING_AUTH = 'LOADING_AUTH';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

//User
export const LOADING_PROFILE = 'LOADING_PROFILE';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAIL = 'PROFILE_FAIL';


//Order
export const LOADING_ORDER = 'LOADING_ORDER';
export const ORDERCREATE_SUCCESS = 'ORDERCREATE_SUCCESS';
export const ORDERGET_SUCCESS = 'ORDERGET_SUCCESS';
export const ORDERUPDATE_SUCCESS = 'ORDERUPDATE_SUCCESS';
export const ORDER_FAIL = 'ORDER_FAIL';
export const CLEAR_ORDER = 'CLEAR_ORDER';
