//Fetch
export const REQUEST_PENDING = 'REQUEST_PENDING';
export const REQUEST_RESOLVED = 'REQUEST_RESOLVED';
export const REQUEST_REJECTED = 'REQUEST_REJECTED';

//Cart
export const LOADING_CARTLIST = 'LOADING_CARTLIST';
export const CARTLIST_SUCCESS = 'CARTLIST_SUCCESS';
export const ADD_CARTITEM = 'ADD_CARTITEM';
export const REMOVE_CARTITEM = 'REMOVE_CARTITEM';
export const CHANGE_QUANTITY = 'CHANGE_QUANTITY';
export const CALCULATE_QTYANDPRICE = 'CALCULATE_QTYANDPRICE';
export const SAVE_PAYINFO = 'SAVE_PAYINFO';

//Authentication
export const LOADING_AUTH = 'LOADING_AUTH';
export const GET_AUTHINFO = 'GET_AUTHINFO';
export const UPDATE_USERDATA = 'UPDATE_USERDATA';
export const LOGOUT_AUTH = 'LOGOUT_AUTH';

//User
export const LOADING_PROFILE = 'LOADING_PROFILE';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAIL = 'PROFILE_FAIL';
export const LOADING_USERORDERS = 'LOADING_USERORDERS';
export const USERORDERS_SUCCESS = 'USERORDERS_SUCCESS';
export const USERORDERS_FAIL = 'USERORDERS_FAIL';

//User - Products
export const GET_USERPRODUCTS = 'GET_USERPRODUCTS';
export const CREATE_USERPRODUCT = 'CREATE_USERPRODUCT';

//Order
export const CREATE_ORDER = 'CREATE_ORDER';
export const GET_ORDER = 'GET_ORDER';
export const GET_ORDERLIST = 'GET_ORDERLIST';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const ORDER_FAIL = 'ORDER_FAIL';
export const CLEAR_ORDER = 'CLEAR_ORDER';
